Repository UMC-ERICA/7th-spring-b, pull requests merged in 2024-11, with the labels that each got.

#2 유니/김승윤 - 5주차 미션
  유니-김승윤/spring/.gitignore
  유니-김승윤/spring/build.gradle
  유니-김승윤/spring/gradle/wrapper/gradle-wrapper.jar
  유니-김승윤/spring/gradle/wrapper/gradle-wrapper.properties
  유니-김승윤/spring/gradlew
  유니-김승윤/spring/gradlew.bat
  유니-김승윤/spring/settings.gradle
  유니-김승윤/spring/src/main/java/umc/spring/Application.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/Category.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/FoodType.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/Inquiry.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/Mission.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/Review.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/SocialLogin.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/Store.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/Terms.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/User.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/base/BaseEntity.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/enums/Gender.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/enums/InquiryStatus.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/enums/InquiryType.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/enums/MemberStatus.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/enums/MissionStatus.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/enums/SocialLoginType.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/enums/TermsType.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/images/InquiryImageSave.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/images/ProfileImageSave.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/images/ReviewImageSave.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/images/StoreImageSave.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/mapping/SelectFoodType.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/mapping/UserMission.java
  유니-김승윤/spring/src/main/java/umc/spring/domain/mapping/UserTerms.java
  유니-김승윤/spring/src/main/resources/application.yml
  유니-김승윤/spring/src/test/java/umc/spring/ApplicationTests.java
Labels: 유니/김승윤

#3 5주차 미션_초이
  초이-최아영/spring/.gitattributes
  초이-최아영/spring/.gitignore
  초이-최아영/spring/build.gradle
  초이-최아영/spring/gradle/wrapper/gradle-wrapper.jar
  초이-최아영/spring/gradle/wrapper/gradle-wrapper.properties
  초이-최아영/spring/gradlew
  초이-최아영/spring/gradlew.bat
  초이-최아영/spring/settings.gradle
  초이-최아영/spring/src/main/java/umc/spring/Application.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Category.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Member.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Mission.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Question.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Restaurant.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Review.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Terms.java
  초이-최아영/spring/src/main/java/umc/spring/domain/common/BaseEntity.java
  초이-최아영/spring/src/main/java/umc/spring/domain/enums/Gender.java
  초이-최아영/spring/src/main/java/umc/spring/domain/enums/MemberStatus.java
  초이-최아영/spring/src/main/java/umc/spring/domain/enums/MissionStatus.java
  초이-최아영/spring/src/main/java/umc/spring/domain/enums/QType.java
  초이-최아영/spring/src/main/java/umc/spring/domain/mapping/Agreement.java
  초이-최아영/spring/src/main/java/umc/spring/domain/mapping/FavCategory.java
  초이-최아영/spring/src/main/java/umc/spring/domain/mapping/MemberMission.java
  초이-최아영/spring/src/main/resources/application.properties
  초이-최아영/spring/src/main/resources/application.yml
  초이-최아영/spring/src/test/java/umc/spring/ApplicationTests.java
Labels: 초이/최아영

#4 혁/조용혁 - 5주차 미션
  혁-조용혁/newFolder.txt
  혁-조용혁/umc_spring/.gitattributes
  혁-조용혁/umc_spring/.gitignore
  혁-조용혁/umc_spring/build.gradle
  혁-조용혁/umc_spring/gradle/wrapper/gradle-wrapper.jar
  혁-조용혁/umc_spring/gradle/wrapper/gradle-wrapper.properties
  혁-조용혁/umc_spring/gradlew
  혁-조용혁/umc_spring/gradlew.bat
  혁-조용혁/umc_spring/settings.gradle
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/Application.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/Inquiry.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/InquiryAnswer.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/Member.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/Mission.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/NewEvent.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/PushNotification.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/ReviewAnswer.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/Store.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/Terms.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/common/BaseEntity.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/enums/Gender.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/enums/InquiryType.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/enums/MemberStatus.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/enums/MissionType.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/enums/TermEssential.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/mapping/MyMission.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/mapping/Review.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/mapping/ReviewComment.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/mapping/Tag.java
  혁-조용혁/umc_spring/src/main/java/com/umc/spring/domain/mapping/TermAgreement.java
  혁-조용혁/umc_spring/src/main/resources/application.yml
  혁-조용혁/umc_spring/src/test/java/com/umc/spring/ApplicationTests.java
Labels: 혁/조용혁

#6 6주차 미션_초이
  초이-최아영/spring/.gitignore
  초이-최아영/spring/build.gradle
  초이-최아영/spring/src/main/java/umc/spring/config/QueryDSLConfig.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Mission.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Restaurant.java
  초이-최아영/spring/src/main/java/umc/spring/repository/MemberRepository/MemberRepository.java
  초이-최아영/spring/src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryCustom.java
  초이-최아영/spring/src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryImpl.java
  초이-최아영/spring/src/main/java/umc/spring/repository/MissionRepository/MissionRepository.java
  초이-최아영/spring/src/main/java/umc/spring/repository/MissionRepository/MissionRepositoryCustom.java
  초이-최아영/spring/src/main/java/umc/spring/repository/MissionRepository/MissionRepositoryCustomImpl.java
  초이-최아영/spring/src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepository.java
  초이-최아영/spring/src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryCustom.java
  초이-최아영/spring/src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  초이-최아영/spring/src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/MissionService/MissionQueryService.java
  초이-최아영/spring/src/main/java/umc/spring/service/MissionService/MissionQueryServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/RestaurantService/RestaurantQueryService.java
  초이-최아영/spring/src/main/java/umc/spring/service/RestaurantService/RestaurantQueryServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/MemberDto.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/MissionStatusDto.java
  초이-최아영/spring/src/main/resources/application.properties
Labels: 초이/최아영

#10 7주차 미션_초이
  초이-최아영/spring/build.gradle
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/ApiResponse.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/code/BaseCode.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  초이-최아영/spring/src/main/java/umc/spring/converter/TempConverter.java
  초이-최아영/spring/src/main/java/umc/spring/service/TempService/TempCommandService.java
  초이-최아영/spring/src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/TempService/TempQueryService.java
  초이-최아영/spring/src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/web/controller/TempRestController.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/TempRequest.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/TempResponse.java
  초이-최아영/spring/src/main/resources/application.properties
Labels: 초이/최아영

#11 혁/조용혁 - 7주차 미션
  JYH/umc_spring/build.gradle
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/ApiResponse.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/code/BaseCode.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/code/BaseErrorCode.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/code/ErrorReasonDTO.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/code/ReasonDTO.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/code/status/ErrorStatus.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/code/status/SuccessStatus.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/exception/ExceptionAdvice.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/exception/GeneralException.java
  JYH/umc_spring/src/main/java/com/umc/spring/apiPayload/exception/handler/TempHandler.java
  JYH/umc_spring/src/main/java/com/umc/spring/converter/TempConverter.java
  JYH/umc_spring/src/main/java/com/umc/spring/service/TempService/TempCommandService.java
  JYH/umc_spring/src/main/java/com/umc/spring/service/TempService/TempCommandServiceImpl.java
  JYH/umc_spring/src/main/java/com/umc/spring/service/TempService/TempQueryService.java
  JYH/umc_spring/src/main/java/com/umc/spring/service/TempService/TempQueryServiceImpl.java
  JYH/umc_spring/src/main/java/com/umc/spring/web/controller/TempRestController.java
  JYH/umc_spring/src/main/java/com/umc/spring/web/dto/TempRequest.java
  JYH/umc_spring/src/main/java/com/umc/spring/web/dto/TempResponse.java
Labels: 혁/조용혁

#15 8주차 미션_초이
  초이-최아영/spring/build.gradle
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/handler/CategoryHandler.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/handler/MemberHandler.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/handler/MissionHandler.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/handler/RegionHandler.java
  초이-최아영/spring/src/main/java/umc/spring/apiPayload/exception/handler/RestaurantHandler.java
  초이-최아영/spring/src/main/java/umc/spring/config/SwaggerConfig.java
  초이-최아영/spring/src/main/java/umc/spring/converter/FavCategoryConverter.java
  초이-최아영/spring/src/main/java/umc/spring/converter/MemberConverter.java
  초이-최아영/spring/src/main/java/umc/spring/converter/RestaurantConverter.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Member.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Mission.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Region.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Restaurant.java
  초이-최아영/spring/src/main/java/umc/spring/domain/Review.java
  초이-최아영/spring/src/main/java/umc/spring/domain/enums/Gender.java
  초이-최아영/spring/src/main/java/umc/spring/domain/mapping/FavCategory.java
  초이-최아영/spring/src/main/java/umc/spring/domain/mapping/MemberMission.java
  초이-최아영/spring/src/main/java/umc/spring/repository/CategoryRepository/CategoryRepository.java
  초이-최아영/spring/src/main/java/umc/spring/repository/MemberMissionRepository/MemberMissionRepository.java
  초이-최아영/spring/src/main/java/umc/spring/repository/RegionRepository.java
  초이-최아영/spring/src/main/java/umc/spring/repository/ReviewRepository.java
  초이-최아영/spring/src/main/java/umc/spring/service/CategoryService/CategoryQueryService.java
  초이-최아영/spring/src/main/java/umc/spring/service/CategoryService/CategoryQueryServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/MemberService/MemberCommandService.java
  초이-최아영/spring/src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/MissionService/MemberMissionService.java
  초이-최아영/spring/src/main/java/umc/spring/service/MissionService/MemberMissionServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/RegionService/RegionService.java
  초이-최아영/spring/src/main/java/umc/spring/service/RegionService/RegionServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/service/RestaurantService/RestaurantService.java
  초이-최아영/spring/src/main/java/umc/spring/service/RestaurantService/RestaurantServiceImpl.java
  초이-최아영/spring/src/main/java/umc/spring/validation/annotation/ChallengingMission.java
  초이-최아영/spring/src/main/java/umc/spring/validation/annotation/ExistCategories.java
  초이-최아영/spring/src/main/java/umc/spring/validation/annotation/ExistCategory.java
  초이-최아영/spring/src/main/java/umc/spring/validation/annotation/ExistRegion.java
  초이-최아영/spring/src/main/java/umc/spring/validation/annotation/ExistRestaurant.java
  초이-최아영/spring/src/main/java/umc/spring/validation/validator/CategoriesExistValidator.java
  초이-최아영/spring/src/main/java/umc/spring/validation/validator/CategoryExistValidator.java
  초이-최아영/spring/src/main/java/umc/spring/validation/validator/ChallengingMissionValidator.java
  초이-최아영/spring/src/main/java/umc/spring/validation/validator/RegionExistValidator.java
  초이-최아영/spring/src/main/java/umc/spring/validation/validator/RestaurantExistValidator.java
  초이-최아영/spring/src/main/java/umc/spring/web/controller/MemberRestController.java
  초이-최아영/spring/src/main/java/umc/spring/web/controller/RestaurantRestController.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/MemberResponseDTO.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/RestaurantRequestDTO.java
  초이-최아영/spring/src/main/java/umc/spring/web/dto/RestaurantResponseDTO.java
Labels: 초이/최아영
